import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import detectEthereumProvider from "@metamask/detect-provider";
import Web3 from "web3";
import { ethers } from "ethers";
import Link from "next/link";
import topLogoImage from "../public/top.svg";
import connectWalletImage from "../public/index/connectWalletButton.svg";
import sub from "../public/index/Subtract.svg";
import SbtIssue from "./SbtIssue";
import style from "../styles/bgimage.module.css";

const Home: NextPage = () => {
  const [account, setAccount] = useState<string>("");

  const connectWallet = () => {
    if (typeof globalThis.window?.ethereum !== "undefined") {
      window.ethereum
        .request({ method: "eth_requestAccounts" })
        .then((accounts) => {
          setAccount(accounts[0]);
        });
    } else {
      console.log("MetaMask is NOT Installed!!");
    }
  };
  return (
    <div>
      <Head>
        <title>zkScore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={style.bg}>
        <div>
          {account !== "" ? (
            // TODO accountの値を<SbtIssue />引数に入れる？→Reduxになるかも。。
            <SbtIssue />
          ) : (
            <div className="h-screen w-screen flex justify-center items-center">
              <Image
                src={topLogoImage}
                alt="logo"
                width={670}
                height={670}
                onClick={connectWallet}
                className="cursor-pointer"
              />
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default Home;
