import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import detectEthereumProvider from "@metamask/detect-provider";
import Web3 from "web3";
import { ethers } from "ethers";
import Link from "next/link";
import Top from "./Top";

import connectWalletImage from "../public/index/connectWalletButton.svg";
import sub from "../public/index/Subtract.svg";

const Home: NextPage = () => {
  const [account, setAccount] = useState<string>("");
  const connectWallet = () => {
    if (typeof globalThis.window?.ethereum !== "undefined") {
      window.ethereum
        .request({ method: "eth_requestAccounts" })
        .then((accounts) => {
          setAccount(accounts[0]);
        });
    } else {
      console.log("MetaMask is NOT Installed!!");
    }
  };
  return (
    <div>
      <Head>
        <title>zkScore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          {account !== "" ? (
            <Top />
          ) : (
            // TODO top,leftのpxハードコード修正？画像を小さくしたい。
            <div className="h-screen w-screen flex justify-center items-center relative">
              <div className="absolute w-fit h-fit top-[100px] left-[330px] z-[0]">
                <Image src={sub} alt="connect" />
              </div>
              <div className="absolute h-fit top-[542px] left-[514px] z-[10] w-fit">
                <Image
                  src={connectWalletImage}
                  alt="connect"
                  onClick={connectWallet}
                />
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default Home;
