import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import detectEthereumProvider from "@metamask/detect-provider";
import Web3 from "web3";
import { ethers } from "ethers";
import Link from "next/link";
import Top from "./Top";

const Home: NextPage = () => {
  const [account, setAccount] = useState<string>("");
  const connectWallet = () => {
    if (typeof globalThis.window?.ethereum !== "undefined") {
      window.ethereum
        .request({ method: "eth_requestAccounts" })
        .then((accounts) => {
          // Return the account of the wallet
          setAccount(accounts[0]);
        });
    } else {
      console.log("MetaMask is NOT Installed!!");
    }
  };
  return (
    <div>
      <Head>
        <title>zkScore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          {account !== "" ? (
            <Top />
          ) : (
            // <Issue />
            <div className={`cube mt-[250px]`}>
              <p className="text-black text-6xl">zkScore</p>
              <button className={"btn-normal"} onClick={connectWallet}>
                Connect Wallet
              </button>
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default Home;
